user lerner;

error_log /home/lerner/Cursor/Prog_Eng/MAI-Backend/lesson-02/logs/error.log info;
pid /home/lerner/Cursor/Prog_Eng/MAI-Backend/lesson-02/nginx.pid;

worker_processes 2;

events {
    worker_connections 64;
}

http {
    access_log /home/lerner/Cursor/Prog_Eng/MAI-Backend/lesson-02/logs/access.log;
    log_format simple '$remote_addr $request $status';

    upstream gunicorn_backend {
        server 127.0.0.1:8000;
    }

    server {
        listen 80;
        server_name localhost;

        # Static files from public/
        location /public/ {
            alias /home/lerner/Cursor/Prog_Eng/MAI-Backend/lesson-02/public/;
            autoindex on;
        }

        # Proxy to gunicorn WSGI app
        location /gunicorn/ {
            proxy_pass http://gunicorn_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
